%% Get the equality constraints of flow conservation
% Args:
%   x: the variables of the optimization problem
%   G: the generated bytes of each sample
%   N_cnt: the number of grid locations
%   xform: the format of the variables
%
% Return:
%   Z: a (N_cnt+1) * 1 vector which should be equal to zero

function Z = flow(x, G, N_cnt, xform)
% initialization
v_cnt = size(x, 1);                % number of variables

% get the transformation matrix to extract x and eta
T_x = [eye(xform.x_cnt), zeros(xform.x_cnt, v_cnt-xform.x_end)];
T_eta = [zeros(xform.eta_cnt, xform.eta_base), eye(xform.eta_cnt), ...
    zeros(xform.eta_cnt, v_cnt - xform.eta_end)];

% extract flow matrix fij (N_cnt * N_cnt) from x
T_fij = [zeros(xform.fij_cnt, xform.fij_base), eye(xform.fij_cnt), ...
    zeros(xform.fij_cnt, v_cnt - xform.fij_end)];
fij = T_fij * x;
fij = reshape(fij, N_cnt, N_cnt)'; % (i, j) is flow from i to j 
% extract flow to sink fiB (N_cnt * 1) from x
T_fiB = [zeros(xform.fiB_cnt, xform.fiB_base), eye(xform.fiB_cnt)];
fiB = T_fiB * x;                   % (i) is flow from i to B

% get the flow conservation at each grid point, Z is N_cnt * 1 here
Z = G * (T_x * x) .* (T_eta * x) + sum(fij, 1)' ... % in flow, sum of each col
    - sum(fij, 2) - fiB;                            % out flow, sum of each row
% all flows should be transmitted to sink
to_sink = sum(G * (T_x * x) .* (T_eta * x)) - sum(fiB);
% combine together to the (N_cnt+1) * 1 vector
Z = [Z; to_sink];
end

